---
- name: "configure mongodb {{ mongodb_version }} apt keyring"
  ansible.builtin.copy:
    src: "server-{{ mongodb_version }}.asc"
    dest: "{{ mongodb_apt_keyring }}"
    owner: root
    group: root
    mode: '0644'

- name: configure mongodb apt sources
  ansible.builtin.copy:
    content: |
      Types: deb
      URIs: {{ mongodb_apt_uri }}
      Suites: {{ mongodb_apt_suites }}
      Components: {{ mongodb_apt_components }}
      Architectures: {{ mongodb_apt_arch }}
      Signed-By: {{ mongodb_apt_keyring }}
    dest: "{{ mongodb_apt_sources }}"
    owner: root
    group: root
    mode: '0644'
  register: mongodb_apt_sources

- name: install mongodb
  ansible.builtin.apt:
    name: "{{ mongodb_packages }}"
    state: present
    update_cache: "{{ mongodb_apt_sources.changed }}"
