---
- name: download omada deb
  ansible.builtin.get_url:
    url: "{{ omada_deb_url }}"
    dest: "/var/cache/{{ omada_deb_basename }}"
    checksum: "{{ omada_deb_checksum }}"
    owner: root
    group: root
    mode: '0644'

- name: install omada packages
  ansible.builtin.apt:
    name: "{{ omada_packages }}"
    state: present

- name: install omada deb
  ansible.builtin.apt:
    deb: "/var/cache/{{ omada_deb_basename }}"
    state: present
