---
- name: install omada packages
  import_tasks: install.yml
  tags:
    - omada
    - omada-install

- name: configure omada service
  service:
    name: "{{ omada_service }}"
    state: "{{ omada_service_state }}"
    enabled: "{{ omada_service_enabled }}"
  tags:
    - omada
  when: ansible_virtualization_type != 'docker'
