---
- name: 'restart omada'
  service:
    name: "{{ omada_service }}"
    state: restarted
  tags:
    - omada
    - omada-config
  when:
    - ansible_virtualization_type != 'docker'
    - omada_service_state != 'stopped'
