---
- name: 'download beta unifi software'
  get_url:
    url: "{{ unifi_beta.base_url | default('https://dl.ui.com/unifi') }}/{{ unifi_beta.version }}/unifi_sysvinit_all.deb"
    dest: "/var/cache/unifi_sysvinit_all-{{ unifi_beta.version }}.deb"
    checksum: "{{ unifi_beta.checksum }}"
    owner: root
    group: root
    mode: '0644'

- name: 'install unifi base packages'
  apt:
    state: present
    name: "{{ unifi_packages_base }}"

- name: 'install unifi beta controller package'
  apt:
    state: present
    deb: "/var/cache/unifi_sysvinit_all-{{ unifi_beta.version }}.deb"
