---
- name: restart unifi
  ansible.builtin.service:
    name: "{{ unifi_service }}"
    state: restarted
  tags:
    - unifi
    - unifi-config
  when:
    - ansible_virtualization_type != 'docker'
    - unifi_service_state != 'stopped'
