---
mongodb_apt_uri: "http://repo.mongodb.org/apt/{{ ansible_distribution | lower }}"
mongodb_apt_suites:
  - "{{ ansible_distribution_release }}/mongodb-org/{{ mongodb_version }}"
mongodb_apt_components:
  - multiverse
mongodb_packages:
  - mongodb-org-server
mongodb_service: mongod
mongodb_service_state: started
mongodb_service_enabled: true
mongodb_version: '4.4'
